#!/bin/sh

jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js\?$' | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

diffs=$(node_modules/.bin/prettier -l $jsfiles)
[ -z "$diffs" ] && exit 0

echo 'Prettifying Javascript...'
node_modules/.bin/prettier --write "$diffs"
git add $diffs
